name: shifra

services:
  # Main application backend
  shifra-backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://shifra_user:shifra_pass@shifra-postgres:5432/shifra_db
      - REDIS_URL=redis://shifra-redis:6379
      - QDRANT_HOST=shifra-qdrant
      - LITELLM_BASE_URL=http://litellm-proxy:4000
      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY:-shifra-master-key}
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret-here}
      - PRIVATEMODE_API_KEY=${PRIVATEMODE_API_KEY:-}
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - LOG_LLM_PROMPTS=${LOG_LLM_PROMPTS:-false}
    depends_on:
      - shifra-postgres
      - shifra-redis
      - shifra-qdrant
      - litellm-proxy
    ports:
      - "58000:8000"
    volumes:
      - ./backend:/app
      - ./logs:/app/logs
    networks:
      - conf-ai-net
    restart: unless-stopped

  # Next.js frontend
  shifra-frontend:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:58000
      - NEXT_PUBLIC_WS_URL=ws://localhost:58000
      - INTERNAL_API_URL=http://shifra-backend:8000
    depends_on:
      - shifra-backend
    ports:
      - "53000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - conf-ai-net
    restart: unless-stopped

  # PostgreSQL database
  shifra-postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=shifra_db
      - POSTGRES_USER=shifra_user
      - POSTGRES_PASSWORD=shifra_pass
    volumes:
      - shifra-postgres-data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    networks:
      - conf-ai-net
    restart: unless-stopped

  # Redis for caching and message queue
  shifra-redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - shifra-redis-data:/data
    networks:
      - conf-ai-net
    restart: unless-stopped

  # LiteLLM proxy for unified LLM API
  litellm-proxy:
    image: ghcr.io/berriai/litellm:main-latest
    environment:
      - UI_USERNAME=admin
      - UI_PASSWORD=${LITELLM_UI_PASSWORD:-admin123}
      - DATABASE_URL=postgresql://shifra_user:shifra_pass@shifra-postgres:5432/shifra_db
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      #- OLLAMA_BASE_URL=http://shifra-ollama-proxy:11434/v1
      #- OLLAMA_API_KEY=ollama
      - PRIVATEMODE_API_KEY=${PRIVATEMODE_API_KEY:-}
      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
      - LITELLM_UI_PASSWORD=${LITELLM_UI_PASSWORD:-admin123}
    volumes:
      - ./litellm_config.yaml:/app/config.yaml
    command: --config /app/config.yaml --port 4000 --num_workers 1
    depends_on:
      - shifra-postgres
    ports:
      - "54000:4000"
    networks:
      - conf-ai-net
    restart: unless-stopped

  # Ollama Free Model Proxy
  #shifra-ollama-proxy:
  #  build: 
  #    context: /home/lio/cloud/code/ollama-free-model-proxy
  #    dockerfile: Dockerfile
  #  environment:
  #    - OPENAI_API_KEY=${OPENROUTER_API_KEY}
  #    - FREE_MODE=true
  #    - TOOL_USE_ONLY=false
  #  volumes:
  #    - shifra-ollama-data:/data
  #  working_dir: /data
  #  networks:
  #    - conf-ai-net
  #  restart: unless-stopped
    #healthcheck:
    #  test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:11434/"]
    #  interval: 30s
    #  timeout: 10s
    #  retries: 3
    #  start_period: 40s

  # Qdrant vector database
  shifra-qdrant:
    image: qdrant/qdrant:latest
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    ports:
      - "56333:6333"  # HTTP API and Web Interface
      - "56334:6334"  # GRPC API (optional)
    volumes:
      - shifra-qdrant-data:/qdrant/storage
    networks:
      - conf-ai-net
    restart: unless-stopped

  # Privatemode.ai service (optional - for confidential models)
  privatemode-proxy:
    image: ghcr.io/edgelesssys/privatemode/privatemode-proxy:latest
    environment:
      - PRIVATEMODE_API_KEY=${PRIVATEMODE_API_KEY:-}
      - PRIVATEMODE_CACHE_MODE=${PRIVATEMODE_CACHE_MODE:-none}
      - PRIVATEMODE_CACHE_SALT=${PRIVATEMODE_CACHE_SALT:-}
    entrypoint: ["/bin/privatemode-proxy"]
    command: [
      "--apiKey=${PRIVATEMODE_API_KEY}",
      "--port=8080"
    ]
    ports:
      - "58080:8080"
    networks:
      - conf-ai-net
    restart: unless-stopped

volumes:
  shifra-postgres-data:
  shifra-redis-data:
  shifra-qdrant-data:
#  shifra-ollama-data:

networks:
  conf-ai-net:
    driver: bridge
